---
strimzi_version: "1.0.0"
strimzi_namespace: kafka
strimzi_operator_manifest_url: "https://github.com/strimzi/strimzi-kafka-operator/releases/download/{{ strimzi_version }}/strimzi-cluster-operator-{{ strimzi_version }}.yaml"
kafka_cluster_name: qoms-kafka
kafka_topic_name: queue-and-occupancy-events
kafka_replicas: 1
kafka_partitions: 1
kafka_replication_factor: 1
kafka_storage_size: 5Gi
kafka_memory_request: 512Mi
kafka_memory_limit: 1Gi
kafka_cpu_request: 250m
kafka_cpu_limit: "1"
strimzi_render_dir: "{{ lookup('env', 'TEMP') | default('/tmp', true) }}/qoms-strimzi"
