deployment:
  kong:
    enabled: true

ingressController:
  enabled: true
  gatewayDiscovery:
    enabled: true
  installCRDs: true

proxy:
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  tls:
    enabled: false

admin:
  enabled: false

env:
  database: "off"
  router_flavor: expressions
  nginx_worker_processes: "1"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
