apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: platform-istio-base
    app.kubernetes.io/part-of: qoms
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.29.0
      helm:
        valueFiles:
          - $values/k8s/platform/istio/base-values.yaml
    - repoURL: https://github.com/AASevastyanov/ProgInj-Block1.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: platform-istiod
    app.kubernetes.io/part-of: qoms
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.29.0
      helm:
        valueFiles:
          - $values/k8s/platform/istio/istiod-values.yaml
    - repoURL: https://github.com/AASevastyanov/ProgInj-Block1.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: platform-istio-policies
    app.kubernetes.io/part-of: qoms
spec:
  project: default
  source:
    repoURL: https://github.com/AASevastyanov/ProgInj-Block1.git
    targetRevision: main
    path: k8s/platform/istio-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: qoms-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
