meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  extensionProviders:
    - name: qoms-otel
      opentelemetry:
        service: opentelemetry-collector.qoms-observability.svc.cluster.local
        port: 4317
  defaultProviders:
    tracing:
      - qoms-otel
  defaultConfig:
    tracing:
      sampling: 20
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"

pilot:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi
