namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.9/manifests/install.yaml

patches:
  - target:
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: redis:7-alpine
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
