apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: block2-data
  namespace: argocd
  labels:
    app.kubernetes.io/name: block2-data
    app.kubernetes.io/part-of: qoms
spec:
  project: default
  source:
    repoURL: https://github.com/AASevastyanov/ProgInj-Block1.git
    targetRevision: main
    path: argocd/data
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
