fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true
  adminPassword: admin
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.qoms-observability.svc.cluster.local
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.qoms-observability.svc.cluster.local:3100
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 3d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
